# Generated by Django 4.2.4 on 2023-09-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(default='user', max_length=200),
            preserve_default=False,
        ),
    ]
